config/routes.rb
Rails.application.routes.draw do
  get 'articles/show'

  get 'articles/new'

  resources :users do
    resources :educations, only: [:create]
  end

  resources :articles
  resources :tasks
  resources :statistics, only: [:index, :show]
  # resources :documents TODO fix file-stuf

  root to: "users#user_root"

  # Custom routes
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_SSN_REGEX = /\A[0-9]{6}-[0-9]{4}/i
  attr_accessor :remember_token
  has_and_belongs_to_many :tasks, dependent: :nullify
  has_many :articles, dependent: :nullify
  has_many :educations, dependent: :destroy
  has_one :contact_person, dependent: :destroy
  belongs_to :role

  accepts_nested_attributes_for :contact_person

  before_save { self.email = email.downcase }
  before_save { self.full_name = "#{self.first_name} #{self.last_name}" }

  # Fuzzy search for user name, last name and first name
  scope :search, -> (query) { where "lower(user_name) like ? or lower(last_name) like ? or lower(first_name) like ?",
                                  "%#{query.downcase}%", "%#{query.downcase}%", "%#{query.downcase}%" }
  scope :sort, -> (condition) { order("#{condition} desc") }

  validates :user_name,      presence: true,
                             length: { in: 4..100 },
                             uniqueness: true

  validates :first_name,     length: { in: 4..100 }, allow_blank: true

  validates :last_name,      length: { in: 4..100 }, allow_blank: true

  validates :password,       presence: true,
                             length: { in: 6..100 }

  validates :email,          length: { maximum: 255 },
                             format: { with: VALID_EMAIL_REGEX },
                             uniqueness: { case_sensitive: false },
                             allow_blank: true

  validates :ssn,            format: { with: VALID_SSN_REGEX },
                             uniqueness: true,
                             allow_blank: true

  validates :phone_number,   length: { in: 7..15 },
                             allow_blank: true


  has_secure_password

  # Remember me token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # "Remembers" a user instance
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # "Forgets" a user instance
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Return hash value of param string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def admin?
    correct_role? :admin
  end

  def editor?
    correct_role? :editor
  end

  def human_resources?
    correct_role? :human_resources
  end

  def project_manager?
    correct_role? :project_manager
  end

  # Checks a remember token
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  private
    def correct_role?(role_name_id)
      self.role.role_name_id == role_name_id.to_s
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Controller that handles everything about the users.
  # Creates, updates, destroys & reads.
  before_action :check_privilege, only: [:new, :create, :destroy, :index]
  before_action :check_if_logged_in, only: [:show, :index, :create, :destroy, :new]

  USER_NAME        = "Användarnamn"
  FIRST_NAME       = "Förnamn"
  LAST_NAME        = "Efternamn"
  EMAIL            = "E-post"
  REGISTERED       = "Registrerad"
  RISING           = "Stigande"
  USER_WAS_REMOVED  = " är borttagen från systemet"
  USER_WAS_UPDATED = "Användaren uppdaterades"

  def new
    @user = User.new

    # This creates the form fields for the nested attributes (contact person)
    @user.build_contact_person
  end

  def index
    # Determine sort condition
    condition = :full_name if params[:sort].nil?
    sort_order = :asc if params[:sort_order].nil?
    # paging_size = 5 if params[:paging_size].nil?

    if params[:paging_size].nil?
      paging_size = 5
    else
      paging_size = params[:paging_size]
    end



    @user = User.new
    @user.build_contact_person

    case params[:sort]
    when USER_NAME
      condition = :user_name
    when FIRST_NAME
      condition = :first_name
    when LAST_NAME
      condition = :last_name
    when EMAIL
      condition = :email
    when REGISTERED
      condition = :created_at
    end



    if params[:sort_order] == RISING
      sort_order = :asc
    else
      sort_order = :desc
    end

    # Paginated users. Change ":per_page" value to get more/less users per page
    if params[:search]
      # User.order instead of search for sort-order (asc and desc)
      @users = User.order(condition => sort_order).paginate(:page => params[:page], :per_page => paging_size).search(params[:search])
    else
      @users = User.order(condition => sort_order).paginate(:page => params[:page], :per_page => paging_size)
    end
    # Responds to js because of ajax.
    respond_to do |format|
      format.js # index.js.erb
      format.html # intex.html.erb
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = @user.first_name + USER_WAS_REMOVED
    redirect_to users_path
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.role = Role.find(user_params[:role_id])
    end

    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = USER_WAS_UPDATED
      redirect_to @user
    else
      render 'edit'
    end
  end

  # Redirects to login or current user depending on if you're logged in
  def user_root
    if logged_in?
      redirect_to current_user
    else
      redirect_to login_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  # Strong parameters that whitelists params that is used in this controller.

  def user_params
    params.require(:user).permit(:user_name, :first_name, :last_name, :password, :password_confirmation, :phone_number, :ssn, :email, :role_id,
                                 contact_person_attributes: [:id, :full_name, :email, :phone_number])
                                 # ^ Nested attributes for contact_person
  end

  def check_privilege
    redirect_to current_user unless current_user.admin? ||
                                    current_user.human_resources?
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_dashboard.html.erb
<div class="btn-group" role="group" aria-label="...">
  <%= link_to "Visa anställda", users_path, class: "btn btn-default" %>
  <%= link_to "Ny artikel", new_article_path, class: "btn btn-default" %>
  <%= link_to "Visa alla artiklar", articles_path, class: "btn btn-default" %>
  <%= link_to "Lägg till uppgift", new_task_path, class: "btn btn-default" %>
  <%= link_to "Visa uppgifter", tasks_path, class: "btn btn-default" %>
  <%= link_to "Statistik", statistics_path, class: "btn btn-default" %>
</div>

app/views/users/_education_display.html.erb
<% @user.educations.each do |education| %>
  <div>
    <p><strong><%= education.name %></strong></p>
    <p>Skola: <%= education.school %></p>
    <p>Tog examen: <%= education.graduation.strftime("%F") %></p>
  </div>
<% end %>

app/views/users/_user_display.html.erb
<div id="user-list-action">
  <div id="list-sort">

    <%= form_tag(params, method: :get, remote: true) do %>
      <p>Välj sortering</p>
      <%= select_tag(:sort, options_for_select(['Användarnamn', 'Förnamn', 'Efternamn', 'E-post', 'Registrerad'], params[:sort])) %>
      <%= select_tag(:sort_order, options_for_select(['Stigande', 'Fallande'], params[:sort_order])) %>

      <%= submit_tag "Sortera", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div id="user-list">
  <ul class="list-group">
    <li class="panel panel-primary panel-user list-head" id="user-list-header">
      <span class="fullname wide">Efternamn, Förnamn</span>
      <span class="fullname responsive">Efternamn, Förnamn / E-post</span>
      <span class="username">Användarnamn</span>
      <span class="email">E-post</span>
      <span class="useraction"></span>
    </li>
    <% @users.each do |user| %>
      <!-- Doesn't show admin. So that admin doesn't fire admin -->
      <% next if user.admin? %>
      <li class="list-group-item">
        <span class="fullname">
          <%= link_to user do %>
            <%= user.last_name %>, <%= user.first_name %>
          <% end %>
          <div class="responsive-email"><%= user.email %></div>
        </span>
        <span class="username">
          <%= link_to user do %>
            <%= user.user_name %>
          <% end %>
        </span>
        <span class="email"><%= user.email %></span>
        <span class="useraction"><%= link_to "Ta bort", user_path(user), method: :delete, data: { confirm: "Vill du verkligen sparka den här personen?"}, class: "fire-link" %></span>
      </li>
    <% end %>
  </ul>
</div>
<div id="user-list-bottom">
  <div id="users-count">Antal: <%= @users.count %></div>

  <%= form_tag(params, method: :get, remote: true) do %>
    <div id="users-per-page">Visa per sida: <%= select_tag(:paging_size, options_for_select(['5', '10', '15', '20', '25'], params[:paging_size])) %> <%= submit_tag "Verkställ", class: "btn btn-primary" %> </div>

  <% end %>
  <div id="paginate">
    <div class="wide"><%= js_will_paginate @users, inner_window: 5, outer_window: 0 %></div>
    <div class="responsive"><%= js_will_paginate @users, inner_window: 1, outer_window: 0 %></div>
  </div>
</div>

app/views/users/create.js.erb
<% if @user.valid? %>
  $('<li class="list-group-item"><span><%= link_to @user do %><%= @user.last_name %>, <%= @user.first_name %><% end %></span><span><%= link_to @user.user_name, @user %></span><span><%= @user.email %></span><span><%= link_to "Ta bort", user_path(@user), method: :delete, data: { confirm: "Vill du verkligen sparka den här personen?"}, class: "fire-link" %></span></li>').insertAfter('#user-list-header');
  $('#success-create-user').html("<div class='alert alert-success'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a>Användare tillagd!</div>");

  // Clear form after successful create
  $('#new_user').trigger("reset");

  // Clear error messages
  $('#user-errors').html("");

  // Collapse form
  $('#toggle-user-form').click();
<% else %>
  $('#user-errors').html("<%= j(render :partial => 'shared/error_messages', locals: {obj: @user}) %>");
<% end %>

app/views/users/edit.html.erb
<% content_for :title, "Profilinställningar" %>

<h3>Ändring av profil</h3>
<p>Obligatoriska fält är markerade med *</p>

<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', obj: f.object %>
    <div class="form-group">
      <%= f.label :user_name, "* Användarnamn" %>
      <%= f.text_field :user_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :first_name, "Förnamn" %>
      <%= f.text_field :first_name, class: "form-control", placeholder: "ex. Mats" %>
    </div>

    <div class="form-group">
      <%= f.label :last_name, "Efternamn" %>
      <%= f.text_field :last_name, class: "form-control", placeholder: "ex. Carlsson" %>
    </div>

    <div class="form-group">
      <%= f.label :ssn, "Personnummer" %>
      <%= f.text_field :ssn, class: "form-control", placeholder: "YYMMDD-XXXX" %>
    </div>

    <div class="form-group">
      <%= f.label :email, "Email" %>
      <%= f.email_field :email, class: "form-control", placeholder: "ex. namn@exempel.se" %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number, "Telefonnummer" %>
      <%= f.text_field :phone_number, class: "form-control", placeholder: "ex. 0701234567" %>
    </div>


    <div class="form-group">
      <%= f.label :password, "* Lösenord" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, "* Konfirmera lösenord" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <!-- Nested fields for contact person -->
    <hr />
    <h3>Närmaste kontaktperson</h3>

    <%=  f.fields_for :contact_person do |ff| %>
      <div class="form-group">
        <%= ff.label :full_name, "Namn" %>
        <%= ff.text_field :full_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= ff.label :phone_number, "Telefonnummer" %>
        <%= ff.text_field :phone_number, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= ff.label :email, "Email" %>
        <%= ff.text_field :email, class: "form-control" %>
      </div>
    <% end %>

    <hr />



    <%= f.submit "Spara användare", class: "btn btn-primary", data: { disable_with: "Skapar användare.." } %>
    <%= link_to "Tillbaka", root_path, class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<%= render 'shared/flash_messages' %>
<!-- Search form, sets params[:search] -->
<div id="user-tool">
  <section id="user-tool-header">
    <p>Hantera användare</p>
  </section>
  <section id="tool-action">
    <% if current_user.human_resources? || current_user.admin? %>
    <div data-toggle="collapse" data-target="#user-form" id="toggle-user-form">
        <span id="plus-sign" class="glyphicon glyphicon-plus-sign"></span>
        <span class="text-link">Lägg till ny användare</span>
    </div>
    <% end %>
    <div id="tool-search">
      <%= form_tag(users_path, :method => "get", remote: true) do %>
        <!-- Removes search query from params if search query is empyu -->
        <% if params[:search] == "" %>
          <% params.delete :search %>
        <% end %>

        <%= text_field_tag :search, params[:search], :value => params[:search], maxlength: 100, class: "form-control", id: "user-search-field", placeholder: "Sök användare" %>
        <!-- Empty paragrah is filled with the search query via JavaScript -->
        <p id="search-query-placeholder"></p>
        <%= link_to users_path, class: "btn btn-primary" do %>
            <span class="wide">Rensa sökning</span>
            <span class="responsive">Rensa</span>
        <% end %>
        <button type="submit" class="btn btn-primary" id="user-search-index">Sök</button>
      <% end %>
    </div>
  </section>

  <div id="user-form" class="collapse">
    <section id="tool-user-form">
      <div id="user-errors"></div>
      <div class="form-block top">
        <span class="form-title"><h4>Information om användare</h4></span>
        <%= form_for(@user, remote: true) do |f| %>

          <div class="input input-left">
            <div class="form-group">
              <%= f.label :user_name, "* Användarnamn", class: 'form-tip' %>
              <%= f.text_field :user_name, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :password, "* Lösenord", class: 'form-tip' %>
              <%= f.password_field :password, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :password_confirmation, "* Konfirmera lösenord", class: 'form-tip' %>
              <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
          </div>

          <div class="input input-right">
            <div class="form-group">
              <%= f.label :email, "Email", class: 'form-tip' %>
              <%= f.email_field :email, class: "form-control", placeholder: "ex. namn@exempel.se" %>
            </div>

            <div class="form-group">
              <%= f.label :phone_number, "Telefonnummer", class: 'form-tip' %>
              <%= f.text_field :phone_number, class: "form-control", placeholder: "ex. 0701234567" %>
            </div>
          </div>

          <div class="input input-center">
            <div class="form-group">
              <%= f.label :first_name, "Förnamn", class: 'form-tip' %>
              <%= f.text_field :first_name, class: "form-control", placeholder: "ex. Mats" %>
            </div>

            <div class="form-group">
              <%= f.label :last_name, "Efternamn", class: 'form-tip' %>
              <%= f.text_field :last_name, class: "form-control", placeholder: "ex. Carlsson" %>
            </div>

            <div class="form-group">
              <%= f.label :ssn, "Personnummer", class: 'form-tip' %>
              <%= f.text_field :ssn, class: "form-control", placeholder: "YYMMDD-XXXX" %>
            </div>
          </div>
        </div>

        <!-- Anhörig -->
        <div class="form-block bottom">
          <%= f.fields_for :contact_person do |ff| %>
            <div class="input input-left">
              <span class="form-title"><h4>Närmast anhörig</h4></span>
              <div class="form-group">
                <%= ff.label :full_name, "Namn", class: 'form-tip' %>
                <%= ff.text_field :full_name, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= ff.label :phone_number, "Telefonnummer", class: 'form-tip' %>
                <%= ff.text_field :phone_number, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= ff.label :email, "Email", class: 'form-tip' %>
                <%= ff.text_field :email, class: "form-control" %>
              </div>
            </div>
          <% end %>

          <div class="input input-radios">
            <span class="form-title"><h4>Användarrättigheter</h4></span>
            <div class="form-group userInfo">
              <%= f.label :role, "Välj roll", class: 'form-tip' %>
              <%= f.collection_radio_buttons :role_id, Role.all, :id, :role_name_id, checked: Role.find_by_role_name_id(4).id do |form_builder| %>
                <div>
                 <%= form_builder.radio_button %>
                 <!--<%= form_builder.label %> -->
                 <!-- Cant get the translation to work for form_builder.label, so we take the
                      text, translate it to its counterpart and throw it inside a label-tag -->
                 <label><%= I18n.t form_builder.text, scope: [:activerecord, :attributes, :role, :role_name_ids]  %></label>
                  <span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="right" title="<%= form_builder.object.description %>"></span>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div id="form-bottom">
          <div id="form-info">
            <p>Obligatoriska fält är markerade med en stjärna *</p>
          </div>
          <div id="form-action">
            <% if current_user.human_resources? || current_user.admin? %>
              <button class="btn btn-secondary" onclick="$('#toggle-user-form').click();return false;" id="cancel" data-target="#user-form">Avbryt</button>
              <%= f.submit "Spara användare", class: "btn btn-primary", data: { disable_with: "Skapar användare.." } %>
            <% end %>
          </div>
        </div>
      <% end %>
    </section>
  </div>
  <section id="user_display">
    <%= render 'user_display' %>
  </section>
</div>
<div id="success-create-user"></div>

app/views/users/index.js.erb
$('#user_display').html("<%= j render :partial => 'user_display' %>");

app/views/users/new.html.erb
<% content_for :title, "Registrera" %>

<h3>Registrera ny användare</h3>
<p>Obligatoriska fält är markerade med *</p>
<%= render 'user_form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Hantera anställda</h3>
      </div>
      <div class="panel-body">
        <%= render 'shared/flash_messages' %>
        <h2><%= @user.user_name %></h2>
        <h4><%= @user.full_name %></h4>

        <ul class="nav nav-pills" role="tablist">
          <li role="presentation" class="active"><a href="#info" aria-controls="info" class="text-settings-nav-tabs" role="tab" data-toggle="tab">Personuppgifter</a></li>
          <li role="presentation"><a href="#education" aria-controls="education" class="text-settings-nav-tabs" role="tab" data-toggle="tab">Utbildning</a></li>
          <li role="presentation"><a href="#contacts" aria-controls="contacts" class="text-settings-nav-tabs" role="tab" data-toggle="tab">Kontaktperson</a></li>
        </ul>


          <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="info">
            <p>Personnummer: <%= @user.ssn %></p>
            <p>Email: <%= @user.email %></p>
            <p>Telefonnummer: <%= @user.phone_number %></p>
          </div>


          <div role="tabpanel" class="tab-pane" id="education">
            <div id="education-display"><%= render "education_display" %></div>

            <% if current_user.admin? || current_user == @user %>
              <div id="show-education-form">
                  <span id="plus-sign" class="glyphicon glyphicon-plus-sign"></span>
                  <span class="text-link">Lägg till utbildning</span>
              </div>
              <div id="education-form">
                <div id="education-errors"></div>
                <ul id="education-list-form">
                    <%= form_for [@user, @user.educations.build], remote: true do |f| %>
                    <li class="form-input">
                        <span class="form-label"><%= f.label :name %></span>
                        <span class="form-input"><%= f.text_field :name %></span>
                    </li>
                    <li class="form-input">
                        <span class="form-label"><%= f.label :school %></span>
                        <span class="form-input"><%= f.text_field :school %></span>
                    </li>
                    <li class="form-input">
                        <span class="form-label"><%= f.label :graduation %></span>
                        <span class="form-input"><%= f.date_field :graduation %></span>
                    </li>
                    <li class="form-action">
                      <span class="form-label"></span>
                      <span class="form-input">
                        <button type="button" id="hide-education-form" class="btn btn-secondary">Avbryt</button>
                        <%= f.submit "Konfirmera", class: "btn btn-primary" %>
                      </span>
                    </li>
                    <% end %>
                </ul>
              </div>
            <% end %>
          </div>

          <div role="tabpanel" class="tab-pane" id="contacts">
            <% if @user.contact_person.present? %>
              <p>Namn: <%= @user.contact_person.full_name %></p>
              <p>Telefonnummer: <%= @user.contact_person.phone_number %></p>
              <p>Namn: <%= @user.contact_person.email %></p>
            <% end %>
          </div>
        </div>


        <% if current_user.admin? %>
          <hr />
          <%= link_to "Ändra anställd", edit_user_path(@user) %>
          <% if @user.admin? %>
            <%= render 'admin_dashboard' %>
          <% end %>
        <% end %>

        <% if current_user.human_resources? %>
          <%= link_to "Skapa ny anställd", new_user_path, class: "btn btn-default" %>
          <%= link_to "Visa anställda", users_path, class: "btn btn-default" %>
        <% end %>

      </div>
    </div>
  </div>
</div>