config/routes.rb
Rails.application.routes.draw do
  get 'articles/show'

  get 'articles/new'

  resources :users do
    resources :educations, only: [:create]
  end

  resources :articles
  resources :tasks
  resources :statistics, only: [:index, :show]
  # resources :documents TODO fix file-stuf

  root to: "users#user_root"

  # Custom routes
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/views/layouts/_admin_sidebar.html.erb
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar collapse sidebar-collapse admin-sidebar"> <!-- before bugtest: class="col-sm-3 col-lg-2 sidebar" -->
    <form role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
        </div>
    </form>

    <ul class="nav menu">
        <li>
          <%= link_to current_user do %>
              <span class="glyphicon glyphicon-home"></span> Dashboard
          <% end %>
        </li>
        <li class="sidebar-header"> Hantera</li>
        <li>
          <%= link_to users_path do %>
            <span class="glyphicon glyphicon-user"></span> Användare
          <% end %>
        </li>
        <li>
          <%= link_to articles_path do %>
            <span class="glyphicon glyphicon-star"></span> Nyheter
          <% end %>
        </li>
        <li>
          <%= link_to tasks_path do %>
            <span class="glyphicon glyphicon-tasks"></span> Uppgifter
          <% end %>
        </li>
        <li>
          <%= link_to statistics_path do %>
              <span class="glyphicon glyphicon-signal"></span> Statistik
          <% end %>
        </li>
    </ul>

    <div class="attribution">
        Copyright &copy; 2016
    </div>
</div><!--/.sidebar-->

app/views/layouts/_breadcrumbs.html.erb
<!-- Home -->
<li><%= link_to current_user, class: "glyphicon glyphicon-home" do %><% end %></li>

<% unless @user.nil? %>
	<!-- Users -->
	<% if current_page?('/users') %>
	    <li class="active">Användare</li>
	    <li class="back">
			<%= link_to root_path, class: "text-link" do%>
				<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
			<% end %>
		</li>

	<!-- Users show -->
	<% elsif current_page?(user_path(@user)) %>

		<!-- Current user show -->
		<% if current_user.id == @user.id %>
			<li class="active">Profilsida</li>
		    <li class="back">
				<%= link_to root_path, class: "text-link" do%>
					<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
				<% end %>
			</li>

		<!-- Another user show -->
		<% else %>
			<li class="">Användare</li>
		    <li class="active"><%= @user.first_name %> <%= @user.last_name %></li>
		    <li class="back">
				<%= link_to users_path, class: "text-link" do%>
					<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
				<% end %>
			</li>
		<% end %>

	<!-- Users edit -->
	<% elsif current_page?(user_path(@user) + '/edit') %>

		<!-- Current user edit -->
		<% if current_user.id == @user.id %>
			<li class="active">Profilinställningar</li>
		    <li class="back">
				<%= link_to @user, class: "text-link" do%>
					<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
				<% end %>
			</li>

		<!-- Another user edit -->
		<% else %>
			<li class="">Användare</li>
		    <li class=""><%= @user.first_name %> <%= @user.last_name %></li>
		    <li class="active">Editor</li>
		    <li class="back">
				<%= link_to @user, class: "text-link" do%>
					<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
				<% end %>
			</li>
		<% end %>
	<% end %>
<% else %>

	<!-- Tasks -->
	<% if current_page?('/tasks') %>
	    <li class="active">Uppgifter</li>
	    <li class="back">
			<%= link_to root_path, class: "text-link" do%>
				<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
			<% end %>
		</li>

	<!-- Tasks new -->
	<% elsif current_page?(controller: 'tasks', action: 'new') %>
		<li class="">Uppgifter</li>
		<li class="active">Ny uppgift</li>
		<li class="back">
			<%= link_to tasks_path, class: "text-link" do%>
				<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
			<% end %>
		</li>

	<!-- Statistics -->
	<% elsif current_page?('/statistics') %>
	    <li class="active">Statistik</li>
	    <li class="back">
			<%= link_to root_path, class: "text-link" do%>
				<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
			<% end %>
		</li>

	<!-- Articles -->
	<% elsif current_page?('/articles') %>
		<li class="active">Nyheter</li>
		<li class="back">
			<%= link_to root_path, class: "text-link" do%>
				<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
			<% end %>
		</li>

	<!-- Articles new -->
	<% elsif current_page?(controller: 'articles', action: 'new') %>
		<li class="">Nyheter</li>
		<li class="active">Ny artikel</li>
		<li class="back">
			<%= link_to articles_path, class: "text-link" do%>
				<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
			<% end %>
		</li>

	<!-- Articles show -->
	<% elsif current_page?(controller: 'articles', action: 'show') %>
		<li class="">Nyheter</li>
		<li class="active"><%= @article.title %></li>
		<li class="back">
			<%= link_to articles_path, class: "text-link" do%>
				<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
			<% end %>
		</li>

	<!-- Articles edit -->
	<% elsif current_page?(controller: 'articles', action: 'edit') %>
		<li class="">Nyheter</li>
		<li class=""><%= @article.title %></li>
		<li class="active">Editor</li>
		<li class="back">
			<%= link_to @article, class: "text-link" do%>
				<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
			<% end %>
		</li>

	<!-- Tasks show -->
	<% elsif current_page?(controller: 'tasks', action: 'show') %>
		<li class="">Uppgifter</li>
		<li class="active"><%= @task.title %></li>
		<li class="back">
			<%= link_to tasks_path, class: "text-link" do%>
				<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
			<% end %>
		</li>

	<!-- Tasks show -->
	<% elsif current_page?(controller: 'tasks', action: 'edit') %>
		<li class="">Uppgifter</li>
		<li class=""><%= @task.title %></li>
		<li class="active">Editor</li>
		<li class="back">
			<%= link_to tasks_path, class: "text-link" do%>
				<span id="caret" class="glyphicon glyphicon-menu-left"></span>Tillbaka
			<% end %>
		</li>

	<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#sidebar-collapse"> <!-- before bugtest: class="navbar-toggle collapsed" -->
                <span class="sr-only">Toggle navigation</span>
                <div>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </div>
                <span class="navbar-toggle-text">MENY</span>
            </button>

            <a class="navbar-brand" href="#"><span>intra</span>EV</a>
            <ul class="user-menu">
                <li class="dropdown pull-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <div class="profile-circle"><%= current_user.first_name[0] %><%= current_user.last_name[0] %></div> <div class="profile-header-name"><%= current_user.first_name %><span id="caret" class="glyphicon glyphicon-menu-down"></span></div> </a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                          <%= link_to current_user do %>
                            <span class = "glyphicon glyphicon-user"></span>
                            Profil
                          <% end %>
                        </li>
                        <li>
                          <%= link_to edit_user_path(current_user) do %>
                            <span class = "glyphicon glyphicon-cog"></span>
                            Profilinställningar
                          <% end %>
                        </li>
                        <li>
                            <%= link_to logout_path, method: "delete" do %>
                              <span class = "glyphicon glyphicon-log-out"></span>
                              Logga ut
                            <% end %>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.container-fluid -->
</nav>

<% if current_user.admin? %>
    <%= render 'layouts/admin_sidebar' %>
<% else %>
    <%= render 'layouts/user_sidebar' %>
<% end %>

app/views/layouts/_user_sidebar.html.erb
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar collapse sidebar-collapse user-sidebar"> <!-- before bugtest: class="col-sm-3 col-lg-2 sidebar" -->
    <form role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
        </div>
    </form>

    <ul class="nav menu">
        <li class="active"><a href="#"><span class = "glyphicon glyphicon-dashboard"></span> Dashboard</a></li>
        <li class="parent profile-sidebar">

            <%= link_to current_user do %>
            <div class="sidebar-profile">
                <div class="profile-circle-sidebar">
                    <%= current_user.first_name[0] %><%= current_user.last_name[0] %>
                </div>
                <div class="profile-link">
                    <span class="greeting"></span>
                    <span class="username"><%= current_user.first_name %> <%= current_user.last_name %></span>
                </div>
            </div>
            <% end %>
            <ul class="children collapse in" id="sub-item-1">
                <li>
                    <%= link_to tasks_path do %>
                      <span class = "glyphicon glyphicon-list-alt"></span> Arbetsuppgifter
                    <% end %>
                </li>
                <li>
                    <%= link_to articles_path do %>
                      <span class = "glyphicon glyphicon-bullhorn"></span> Nyheter
                    <% end %>
                </li>
                <li>
                    <a class="user-link" href="#">
                        <span class = "glyphicon glyphicon-scale"></span> Tidsrapport
                    </a>
                </li>
                <li>
                    <a class="user-link" href="#">
                        <span class = "glyphicon glyphicon-calendar"></span> Kalender
                    </a>
                </li>
            </ul>
        </li>
        <li class="sidebar-header"> Verksamheten</li>
        <li><a href="#"><span class = "glyphicon glyphicon-star"></span> Nyheter</a></li>
        <li><a href="#"><span class = "glyphicon glyphicon-road"></span> Målsättning</a></li>
        <li><a href="#"><span class = "glyphicon glyphicon-signal"></span> Processer</a></li>
        <li>
          <%= link_to statistics_path do %>
              <span class="glyphicon glyphicon-signal"></span> Statistik
          <% end %>
        </li>
        <li><a href="#"><span class = "glyphicon glyphicon-book"></span> Lagar &amp; Regler</a></li>
        <li><a href="#"><span class = "glyphicon glyphicon-heart"></span> Arbetsmiljö</a></li>
        <li><a href="#"><span class = "glyphicon glyphicon-tree-conifer"></span> Hållbarhet</a></li>
        <li class="sidebar-header"> Dokument</li>
        <li><a href="#"><span class = "glyphicon glyphicon-folder-open"></span> Styrdokument</a></li>
        <li><a href="#"><span class = "glyphicon glyphicon-folder-open"></span> Redovisande dokument</a></li>
        <li><a href="#"><span class = "glyphicon glyphicon-folder-open"></span> Blanketter</a></li>
    </ul>

    <div class="attribution">
        Copyright &copy; 2016
    </div>
</div><!--/.sidebar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=1,initial-scale=1,user-scalable=1" />
  <title>IntraEV <%= yield :title %></title>
  <link href="//fonts.googleapis.com/css?family=Lato:100italic,100,300italic,300,400italic,400,700italic,700,900italic,900" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
   <%= yield :charts_js %>

  <%= csrf_meta_tags %>
</head>
      <!-- Log out button only if logged in -->
      <% if logged_in? %>
      <body data-no-turbolink="true" id="loggedin">
        <!-- <div id="wrapper"> -->
          <%= render 'layouts/navigation' %>

          <div class="col-xs-12 col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
            <div id="page-top" class="row">
              <ol class="breadcrumb">
                <%= render 'layouts/breadcrumbs' %>
              </ol>
            </div>

            <%= yield %>

            <!-- Debug info, only shown in development (not on heroku) -->
            <%= debug(params) if Rails.env.development? %>

          </div>

      </body>
      <% end %>

      <% if !logged_in? %>
        <body data-no-turbolink="true" id="login">
          <%= yield %>

          <%= debug(params) if Rails.env.development? %>

        </body>
      <% end %>

</html>